### ISSUE TITLE
有哪位大佬可以告诉我再mode 'none'的时候怎么做到的隔离级别

### ISSUE THREAD

**Issue by rexleimo** [tangshuang/mfy#3]
我大佬知道的时候  记得@一下我哦

**Comment by tangshuang** [comment]
> 我大佬知道的时候 记得@一下我哦

mode:none 不会做脚本隔离，只有样式隔离

**Comment by rexleimo** [comment]
> > 我大佬知道的时候 记得@一下我哦
> 
> mode:none 不会做脚本隔离，只有样式隔离

哦哦 看到了 样式隔离是有一个stylerults管理，然后重新加到了每个style中。 看完后 感觉 Micro App 应该是借鉴了你的思路实现的
